### ISSUE TITLE
preview is low resolution

### ISSUE THREAD

**Issue by leon196** [Meta-Ben/DualEditor#1]
Hello,

Thanks for the add-on, this is very useful.
It appears that the preview is not at full resolution, this is a screenshot of project with Godot 4.3:

![image](https://github.com/user-attachments/assets/25d5bde0-e44b-46bd-9da6-3011223d12ea)

I'm looking at trying to fix it but I'm still learning how to use Godot and custom add-ons, so I'm wondering if you know how to resolve it?

**Comment by Meta-Ben** [comment]
Hello ! Just saw your comment, I will try to reproduce the problem !

**Comment by Meta-Ben** [comment]
@leon196 
After some test I didn't succeed to reproduce your bug 

I first tried with a big image as Sprite2D : 
<img width="1496" alt="Capture d’écran 2024-09-24 à 14 30 20" src="https://github.com/user-attachments/assets/e0157df5-8c1e-40a5-82cc-c204f4de8dde">

Then I tried scaling this image to 1000 to see if your problem is caused by a too big image for the previewer but still I can see it fully and clearly :
<img width="1265" alt="Capture d’écran 2024-09-24 à 14 32 59" src="https://github.com/user-attachments/assets/a3209f5c-75be-494f-a3a5-378ab0b50d3e">


Maybe you can help me with some additional info : 

- What contain your 2D view ? 
- Whats the zoom level of your 2D view ( your real 2D view not the previewed one ) 
- If you only have a sprite2D ( whats size ? ) 

Also when you say " the preview is not at full resolution" did you mean that your image in the preview is cropped ? 

Those inputs could help me too fix your issue :)

**Comment by leon196** [comment]
Thanks for the quick reply and taking the time to test.

- What contain your 2D view ?
It's a set of sub viewport containers, in a comic game layout

- Whats the zoom level of your 2D view ( your real 2D view not the previewed one )
I'm not sure about this one, I'm trying to get the render of sub viewport containers to match any resolution.

- If you only have a sprite2D ( whats size ? )
I've tried with a sprite2D and I see it works best, specially when I zoom in details.

Here's a video, it's hard to see quite right the actual resolution because of the compression:
https://github.com/user-attachments/assets/70a1b3a8-7ec7-4e91-8edf-d4d512919c6b

Now  that I've tried with a sprite2D, I think the plugin works as it should. It's how the minification of the texture works.

This is a screenshot of the default 2D view.
![image](https://github.com/user-attachments/assets/1c409b46-05e4-458e-8d75-c0e6506ae475)

And with the previewer.
![image](https://github.com/user-attachments/assets/72fc4598-2915-4da1-b157-7c270f48dbcf)

Since it's hard to tell, here the two close up of the views.
![image](https://github.com/user-attachments/assets/82d0189e-29f3-4394-817e-83599df6caee)
![image](https://github.com/user-attachments/assets/5c5dfbdf-a154-48ab-859f-27eb9c84f724)

My goal is to pin the 2D view, to keep track of the comic layout, so I can update camera placement, while having a global view of the layout. I'll try to interact with the plugin source code a little more and keep you posted if I get something interesting.

**Comment by Meta-Ben** [comment]
Thanks for the huge input you gave me, It's really help me a lot to understand the problem you face ! I will take a look and try to fix this but it could take me some time, if the sprite2D method work go with it for now if you can

**Comment by Meta-Ben** [comment]
@leon196 
I tried to setup my project the same as yours, but even in that I didn't succeed to reproduce your problem, here is my 2D preview quality using subview and control texture node : 

<img width="1487" alt="Capture d’écran 2024-09-29 à 16 15 48" src="https://github.com/user-attachments/assets/64e91eec-bd4e-4c4b-8fec-c1f6045817c0">


And here is the actual 2D control texture node quality in the 2D editor : 
<img width="1470" alt="Capture d’écran 2024-09-29 à 16 16 26" src="https://github.com/user-attachments/assets/a4bdd73d-afd4-425e-99d6-10426d93ed94">


Look like there is no difference for me, maybe try using the "nearest" option in your SubViewPortContainer ( the green one )
<img width="243" alt="Capture d’écran 2024-09-29 à 16 19 02" src="https://github.com/user-attachments/assets/6dfb7e75-fbbd-47cc-9c89-6d2fb27a4258">

**Comment by leon196** [comment]
Interesting, thanks for exploring the issue.
Setting nearest filter will change the rendering of the viewport container, but it still lacks of resolution. I'm playing with container size of the plugin scene, but I'm breaking everything very quickly. I'm not able to look at it further this week, but I'm keen to learn from your plugin to get that second 2D view screen.

**Comment by Meta-Ben** [comment]
I will continue to check when I can, though maybe not with pixel art images. 

Don't hesitate to share your thoughts or progress on your investigation here or in a discussion topic on the repo. I will try to help you as best as I can. 

If you succeed in fixing the problem on your own, don't hesitate to open a PR that I can review and merge for other users who might face the same issue. 😊

**Comment by bencmckenna** [comment]
I just wanted to chime in - I was also having this issue and managed to resolve it by modifying **res://addons/Previewer_2D_3D/Previewer2D3D.tscn**

Both the **Preview** and **TextureRect** control nodes were the wrong size for my editor:
![nodes](https://github.com/user-attachments/assets/cdef1863-3a39-4ed0-b4fc-506f1f60f3c6)
![res](https://github.com/user-attachments/assets/aefb1e13-8145-4bf6-883d-c81208421e52)

So I set them both to **Full Rect**:
![fullrect](https://github.com/user-attachments/assets/79008ec0-cdd9-495f-99c2-6af8d784af6c)

Not sure if it was necessary, but I also changed the **3D_Viewport** and **2D_Viewport** nodes to match the resolution I wanted.

And most importantly, I had to **disable and re-enable the addon** in the editor settings. 

It's a great addon by the way! Very useful for my purposes. 😃

**Comment by Meta-Ben** [comment]
Hello @bencmckenna 

Great finding !!! Thanks a lot for taking the time to dig in I didn't succeed to reproduce so I was a bit blocked to help !

If you want to contribute and open a PR maybe @leon196 could test it too ? then i will merge it into the project ! 😄

**Comment by bencmckenna** [comment]
@Meta-Ben I actually made some modifications so that it swaps between the native 2D/3D editors when I hover the mouse over the preview panel. I find it a bit more intuitive for my purposes, but it's a bit of a departure from your original implementation. 

https://github.com/user-attachments/assets/f105c504-8dd7-4392-8f01-f65effd9a0cd

Would it be worth adding to the PR?

**Comment by Meta-Ben** [comment]
@bencmckenna Its an amazing modification, I really love it !! 

I think it could be nice to implement it in a separate PR ! Like, one for the fix of @leon196 problem and another one with this cool enhancement !

**Comment by Meta-Ben** [comment]
I approved the PR @bencmckenna, are you able to merge it ? ( if not I will do it )

**Comment by bencmckenna** [comment]
@Meta-Ben Thanks! I don't think I can merge it, you'll need to do it on your end :)

**Comment by leon196** [comment]
Hello,

I've tried the pull request but it seems that the layout is out bounds (the gray area in the screenshot below):
![Screenshot from 2024-11-18 09-14-48](https://github.com/user-attachments/assets/0b964990-71c9-4a7c-b0ba-a3c6001b30b5)

At the moment I've come with an alternative where I control the 3D camera by selecting the frame itself
![image](https://github.com/user-attachments/assets/797eb32a-bfdd-4275-87d2-47d72aed1edf)

**Comment by Meta-Ben** [comment]
Thanks for your test @leon196, can you share your godot version + OS ? I think I will do more test on the PR to avoid breaking things
@bencmckenna maybe you can try to open the second PR with the 2D/3D behavior you made on the current base if possible ?

**Comment by leon196** [comment]
that was a screenshot from Godot 4.3 on Zorin OS 17 (Ubuntu 22)

**Comment by Meta-Ben** [comment]
I tried on 4.3 too but on MacOs and no issue 

Mmmmh I think that to avoid breaking thing we can skip the fix for now, see if more people come in this issue or if someone managed to find a workaround or if more tester come for the PR, if the code evolve too much I can make the PR follow the main branch over time

And maybe @bencmckenna you can open a PR without the fix but with your feature enhancement implementation ( 2D/3D switch on panel hover ), what do you think ?

**Comment by bencmckenna** [comment]
@leon196 Thanks for testing! Sorry it didn't work. I'm a bit out of my league working with control nodes so I'm not sure what could be causing the issue... 😅 I'll look into.

@Meta-Ben No problem - I still have a few problems I still need to iron out, but I should be able to make it available for testing later in the week.

**Comment by Meta-Ben** [comment]
Hey @bencmckenna did you got some news ?

**Comment by bencmckenna** [comment]
@Meta-Ben Have cleaned up some of the remaining bugs and made a PR. 😃
